### ISSUE TITLE
APK Reupload

### ISSUE THREAD

**Issue by ayunami2000** [joas8211/ForceDarkModeOreo#3]
I am trying to compile the project and will send the APK if it succeeds. But, in the meantime, if you have the APK you originally uploaded (which is no longer present), please send it. Thank you!

**Comment by joas8211** [comment]
Android 8.0 (API level 26) has received it's final security patch as of January 2021, so this module shouldn't be needed in almost any scenario. If you somehow need this module you can indeed compile it yourself. I suggest not to share or download the APK because I don't want to take any responsibility of someone possibly maliciously modifying the code.

**Comment by ayunami2000** [comment]
I need it for my shitty mini phone I got off Temu, lol. It runs Android 8.1.0.

Android studio doesnt seem to support API level 27 anymore.

**Comment by ayunami2000** [comment]
I got it to compile (somehow). I will let you know if it works.
